# Generated by Django 4.2.29 on 2026-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Image Title')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image File')),
                ('category', models.CharField(choices=[('A', 'Activities'), ('E', 'Events'), ('C', 'Classroom'), ('O', 'Other')], default='O', max_length=1, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show in Gallery')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
