# Generated by Django 4.2.29 on 2026-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Parent Name')),
                ('child_name', models.CharField(max_length=200, verbose_name='Child Name')),
                ('child_age', models.PositiveIntegerField(verbose_name='Child Age (Years)')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('message', models.TextField(blank=True, verbose_name='Message / Query')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted On')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read by Admin')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
