# Generated by Django 4.2.29 on 2026-04-17 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Parent Name')),
                ('child_name', models.CharField(max_length=200, verbose_name='Child Name')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)')),
                ('review_message', models.TextField(verbose_name='Review Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Review Date')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved by Admin')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
